/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;


import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


/**
 *
 * @author hecto
 */
public class UserLogin extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    public UserLogin() {
        initComponents();
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();

        for (TipoIdentificacion tipo : TipoIdentificacion.values()) {
            comboBoxModel.addElement(TipoIdentificacion.fromEnumToString(tipo));
        }

        multipleChoiceUser.setModel(comboBoxModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bienvenido = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        fieldNombreUser = new javax.swing.JTextField();
        apellido = new javax.swing.JLabel();
        fieldApellidoUser = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        fieldEmailUser = new javax.swing.JTextField();
        DNI = new javax.swing.JLabel();
        fieldDniUser = new javax.swing.JTextField();
        identificacionUser = new javax.swing.JLabel();
        multipleChoiceUser = new javax.swing.JComboBox<>();
        iniciarSesionuSER = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        bienvenido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bienvenido.setForeground(new java.awt.Color(102, 102, 102));
        bienvenido.setText("¡Bienvenido!");

        descripcion.setText("Antes de comenzar, es necesario que completes estos campos para poder registrar un expediente");

        nombre.setText("Nombre");

        fieldNombreUser.setForeground(new java.awt.Color(102, 102, 102));
        fieldNombreUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldNombreUser.setToolTipText("Número de administrador");
        fieldNombreUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 15));
        fieldNombreUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreUserActionPerformed(evt);
            }
        });

        apellido.setText("Apellido");

        fieldApellidoUser.setForeground(new java.awt.Color(102, 102, 102));
        fieldApellidoUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldApellidoUser.setToolTipText("Número de administrador");
        fieldApellidoUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 15));
        fieldApellidoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldApellidoUserActionPerformed(evt);
            }
        });

        email.setText("Email");

        fieldEmailUser.setForeground(new java.awt.Color(102, 102, 102));
        fieldEmailUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldEmailUser.setToolTipText("Número de administrador");
        fieldEmailUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 15));
        fieldEmailUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailUserActionPerformed(evt);
            }
        });

        DNI.setText("DNI");

        fieldDniUser.setForeground(new java.awt.Color(102, 102, 102));
        fieldDniUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldDniUser.setToolTipText("Número de administrador");
        fieldDniUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 15));
        fieldDniUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDniUserActionPerformed(evt);
            }
        });

        identificacionUser.setText("Identificacion");

        multipleChoiceUser.setForeground(new java.awt.Color(102, 102, 102));
        multipleChoiceUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opción", "Persona", "Trabajdor", "dada" }));
        multipleChoiceUser.setBorder(null);
        multipleChoiceUser.setLightWeightPopupEnabled(false);
        multipleChoiceUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleChoiceUserActionPerformed(evt);
            }
        });

        iniciarSesionuSER.setBackground(new java.awt.Color(51, 51, 51));
        iniciarSesionuSER.setForeground(new java.awt.Color(255, 255, 255));
        iniciarSesionuSER.setText("Iniciar sesión");
        iniciarSesionuSER.setBorder(null);
        iniciarSesionuSER.setBorderPainted(false);
        iniciarSesionuSER.setFocusPainted(false);
        iniciarSesionuSER.setFocusable(false);
        iniciarSesionuSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionuSERActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("*Si es una institución omitir este campo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(descripcion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(bienvenido))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(apellido)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                    .addComponent(fieldApellidoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(email)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fieldEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DNI)
                                        .addComponent(nombre)
                                        .addComponent(identificacionUser))
                                    .addGap(35, 35, 35)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(multipleChoiceUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fieldNombreUser, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                        .addComponent(fieldDniUser, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))
                                .addComponent(iniciarSesionuSER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(bienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcion)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(fieldNombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellido)
                    .addComponent(fieldApellidoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(fieldEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DNI)
                    .addComponent(fieldDniUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identificacionUser)
                    .addComponent(multipleChoiceUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(iniciarSesionuSER, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNombreUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreUserActionPerformed

    private void fieldApellidoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldApellidoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldApellidoUserActionPerformed

    private void fieldEmailUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmailUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailUserActionPerformed

    private void fieldDniUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDniUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDniUserActionPerformed

    private void iniciarSesionuSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionuSERActionPerformed
        try {
            String nombreValue = fieldNombreUser.getText();
            String apellidoValue = fieldApellidoUser.getText();
            String identificacion = (String) multipleChoiceUser.getSelectedItem();
            String correoElectronicoValue = fieldEmailUser.getText();
            String DNIUser = fieldDniUser.getText();

            if (nombreValue.equals("") || apellidoValue.equals("") || identificacion.equals("") || correoElectronicoValue.equals("")) {
                throw new IllegalArgumentException("Todos los campos son requeridos");
            }
            if (!Utils.Utils.esEmailValido(correoElectronicoValue)) {
                throw new IllegalArgumentException("Correo electrónico no válido");
            }
            User usuarioNuevo = new User(nombreValue, apellidoValue, correoElectronicoValue, TipoIdentificacion.fromStringToEnum(identificacion), DNIUser);

            Servicio.UsersServicios.agregarUsuario(usuarioNuevo);
            dispose();
            UserExpediente userExpediente = new UserExpediente(correoElectronicoValue, nombreValue);
            userExpediente.setVisible(true);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_iniciarSesionuSERActionPerformed

    private void multipleChoiceUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleChoiceUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multipleChoiceUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DNI;
    private javax.swing.JLabel apellido;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel email;
    private javax.swing.JTextField fieldApellidoUser;
    private javax.swing.JTextField fieldDniUser;
    private javax.swing.JTextField fieldEmailUser;
    private javax.swing.JTextField fieldNombreUser;
    private javax.swing.JLabel identificacionUser;
    private javax.swing.JButton iniciarSesionuSER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> multipleChoiceUser;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
