/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfasprueba;
import Servicio.Expediente;
import Servicio.PilaExpedientes;
import TDA.Nodo;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manue
 */
public class ConsultarExpediente extends javax.swing.JFrame {

    
    private PilaExpedientes pilaExpdiente;
    
    public ConsultarExpediente(PilaExpedientes pilaExpdiente) {
        initComponents();

        DependenciaDestino.addItem("Ing. Sistemas");
        DependenciaDestino.addItem("Ing. Industrial");
        DependenciaDestino.addItem("Marketing");
        this.pilaExpdiente = pilaExpdiente;

        agregarDatosATabla();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
         
    }
    private void agregarDatosATabla() {
    DefaultTableModel model = (DefaultTableModel) tablaExpedientes2.getModel();
    List<Expediente> expedientes = new ArrayList<>();
    model.setRowCount(0);
    
    
    
    Nodo<Expediente> nodoActual = this.pilaExpdiente.top;
    while (nodoActual != null) {
        Expediente expediente = nodoActual.getValue();
        expedientes.add(expediente);
        nodoActual = nodoActual.getNext();
    }
    
    // Ordenar la lista de expedientes por prioridad
    Collections.sort(expedientes, new Comparator<Expediente>() {
        @Override
        public int compare(Expediente e1, Expediente e2) {
            String prioridad1 = e1.getPrioridad();
            String prioridad2 = e2.getPrioridad();
            
            if (prioridad1.equals("Alta")) {
                return -1;
            } else if (prioridad1.equals("Media")) {
                if (prioridad2.equals("Alta")) {
                    return 1;
                } else {
                    return -1;
                }
            } else {
                if (prioridad2.equals("Alta") || prioridad2.equals("Media")) {
                    return 1;
                } else {
                    return -1;
                }
            }
        }
    });
    
    // Agregar los expedientes ordenados a la tabla
    for (Expediente expediente : expedientes) {
        model.addRow(new Object[] {
            expediente.getIdentificadorUnico(),
            expediente.getNombres(),
            expediente.getApellidos(),
            expediente.getDNI(),
            expediente.getPrioridad(),
            expediente.getAsunto(),
            expediente.getDependencia(),
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Expediente = new javax.swing.JTextField();
        DependenciaDestino = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        BotonCambiar = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaExpedientes2 = new javax.swing.JTable();
        BotonEliminar = new javax.swing.JButton();
        BotonTiempo = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Consulta de expediente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 260, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 420));

        jLabel2.setText("Identificador");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 80, -1));

        jLabel3.setText("Dependencia Destino");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 120, -1));

        Expediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpedienteActionPerformed(evt);
            }
        });
        jPanel1.add(Expediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 140, -1));

        DependenciaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DependenciaDestinoActionPerformed(evt);
            }
        });
        jPanel1.add(DependenciaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 120, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo ulima.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 90, 90));

        BotonCambiar.setText("Cambiar");
        BotonCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCambiarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 100, 30));

        tablaExpedientes2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nombre", "Apellido", "DNI", "Prioridad", "Asunto", "Dependencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaExpedientes2.setName("tablaExpedientes2"); // NOI18N
        jScrollPane2.setViewportView(tablaExpedientes2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 630, 150));

        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 100, 30));

        BotonTiempo.setText("Conocer Tiempo de Duración");
        BotonTiempo.setToolTipText("");
        BotonTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTiempoActionPerformed(evt);
            }
        });
        jPanel1.add(BotonTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DependenciaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DependenciaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DependenciaDestinoActionPerformed

    private void BotonCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCambiarActionPerformed
        String IdentificadorDeExpediente = Expediente.getText();
        String dependenciaDestino = DependenciaDestino.getSelectedItem().toString();
        
        Nodo<Expediente> nodoActual = this.pilaExpdiente.top;
        while (nodoActual != null) {
            Expediente expedienteActual = nodoActual.getValue();
            //System.out.println("Expediente: " + expedienteActual.getIdentificadorUnico());
            //System.out.println(IdentificadorDeExpediente);
            if (expedienteActual.getIdentificadorUnico().equals(IdentificadorDeExpediente)) {
                expedienteActual.setDependencia(dependenciaDestino);
                JOptionPane.showMessageDialog(this, "Se actualizó la tabla", " ", JOptionPane.ERROR_MESSAGE);
                agregarDatosATabla();
                break;
            }
            nodoActual = nodoActual.getNext();
        }
    }//GEN-LAST:event_BotonCambiarActionPerformed

    private void ExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpedienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpedienteActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
    String IdentificadorDeExpediente = Expediente.getText();
    
    Expediente.setText("");
    
    Nodo<Expediente> nodoActual = this.pilaExpdiente.top;
    Nodo<Expediente> nodoAnterior = null;
    while (nodoActual != null) {
        Expediente expedienteActual = nodoActual.getValue();
        if (expedienteActual.getIdentificadorUnico().equals(IdentificadorDeExpediente)) {
            if (nodoAnterior == null) {
                this.pilaExpdiente.pop();
            } else {
                nodoAnterior.setNext(nodoActual.getNext());
            }
            LocalDateTime fechaEliminacion = LocalDateTime.now();
            String fechaHoraEliminacion = fechaEliminacion.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
            JOptionPane.showMessageDialog(this, "Se eliminó el expediente " + IdentificadorDeExpediente + " a las " + fechaHoraEliminacion, "Expediente eliminado", JOptionPane.INFORMATION_MESSAGE);
            agregarDatosATabla();
            break;
        }
        nodoAnterior = nodoActual;
        nodoActual = nodoActual.getNext();
    }

    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void BotonTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTiempoActionPerformed
        String IdentificadorDeExpediente = Expediente.getText();
        Nodo<Expediente> nodoActual = this.pilaExpdiente.top;
        while (nodoActual != null) {
            Expediente expedienteActual = nodoActual.getValue();
            if (expedienteActual.getIdentificadorUnico().equals(IdentificadorDeExpediente)) {
                LocalDateTime fechaIngreso = expedienteActual.getFechaIngreso();
                LocalDateTime fechaActual = LocalDateTime.now();
                long duracionEnSegundos = java.time.Duration.between(fechaIngreso, fechaActual).getSeconds();
                long minutos = duracionEnSegundos / 60;
                long horas = minutos / 60;
                long dias = horas / 24;
            
                String duracion = String.format("Duración: %d días, %d horas, %d minutos y %d segundos", dias, horas % 24, minutos % 60, duracionEnSegundos % 60);
                JOptionPane.showMessageDialog(this, duracion, "Duración del expediente", JOptionPane.INFORMATION_MESSAGE);
                break;
            }
            nodoActual = nodoActual.getNext();
        }
    }//GEN-LAST:event_BotonTiempoActionPerformed
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
    }
});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonCambiar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JToggleButton BotonTiempo;
    private javax.swing.JComboBox<String> DependenciaDestino;
    private javax.swing.JTextField Expediente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaExpedientes2;
    // End of variables declaration//GEN-END:variables
}
